[build]
  # Build the widget app with pnpm in a monorepo
  command = "pnpm -v && pnpm -w install --frozen-lockfile && pnpm --filter @durmah/widget build"
  publish = "apps/widget/dist"

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "9"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Route API traffic to the lambda function
[[redirects]]
  from = "/v1/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true

# SPA fallback for Vite build
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
