[build]
  command = "npm run build:widget"
  publish = "apps/widget/dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev:widget"
  targetPort = 5173
  port = 8888
  autoLaunch = false

# Proxy all API calls to the Netlify Function
[[redirects]]
  from = "/v1/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
