# Widget deployment
[build]
  command = "pnpm run build"
  publish = "apps/widget/dist"
  base = "/"

[build.environment]
  NODE_VERSION = "20"

# Admin deployment (separate site)
[context.admin]
  command = "cd apps/admin && pnpm run build"
  publish = "apps/admin/.next"

# Redirects
[[redirects]]
  from = "/api/*"
  to = "https://api.durmah.com/:splat"
  status = 200

# Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' https://api.durmah.com; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"
